services:
  backend:
    build: ./backend
    container_name: project1-backend
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: project1-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
